Try to create the backpropagation and feedforward in python by creating function

In [1]:
import numpy as np

# Considering sample data as follows
# X = (hours studying, hours sleeping), y = score on test
xAll = np.array(([2, 9], [1, 5], [3, 6], [5, 10]), dtype=float)  # input data
y = np.array(([92], [86], [89]), dtype=float)  # output

# scale units
xAll = xAll / np.amax(xAll, axis=0)  # scaling input data
y = y / 100  # scaling output data (max test score is 100)

# split data
X = np.split(xAll, [3])[0]  # training data
xPredicted = np.split(xAll, [3])[1]  # testing data

y = np.array(([92], [86], [89]), dtype=float)
y = y / 100  # max test score is 100


class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3

        #weights
        self.W1 = np.random.randn(
            self.inputSize,
            self.hiddenSize)  # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(
            self.hiddenSize,
            self.outputSize)  # (3x1) weight matrix from hidden to output layer

    def forward(self, X):
        #forward propagation through our network
        self.z = np.dot(
            X,
            self.W1)  # dot product of X (input) and first set of 3x2 weights
        self.z2 = self.sigmoid(self.z)  # activation function
        self.z3 = np.dot(
            self.z2, self.W2
        )  # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3)  # final activation function
        return o

    def sigmoid(self, s):
        # activation function
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o):
        # backward propagate through the network
        self.o_error = y - o  # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(
            o)  # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(
            self.W2.T
        )  # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error * self.sigmoidPrime(
            self.z2)  # applying derivative of sigmoid to z2 error

        self.W1 += X.T.dot(
            self.z2_delta)  # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(
            self.o_delta)  # adjusting second set (hidden --> output) weights

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

    def saveWeights(self):
        np.savetxt("w1.txt", self.W1, fmt="%s")
        np.savetxt("w2.txt", self.W2, fmt="%s")

    def predict(self):
        print("Predicted data based on trained weights: ")
        print("Input (scaled): \n" + str(xPredicted))
        print("Output: \n" + str(self.forward(xPredicted)))


NN = Neural_Network()
for i in range(1000):  # trains the NN 1,000 times
    print("# " + str(i) + "\n")
    print("Input (scaled): \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" + str(NN.forward(X)))
    print("Loss: \n" +
          str(np.mean(np.square(y - NN.forward(X)))))  # mean sum squared loss
    print("\n")
    NN.train(X, y)

NN.saveWeights()
NN.predict()

# 0

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.28071431]
 [0.28574698]
 [0.26508506]]
Loss: 
0.37632380018737255


# 1

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.39337803]
 [0.38846107]
 [0.37882587]]
Loss: 
0.2536595503213112


# 2

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.5125027 ]
 [0.49712646]
 [0.50171141]]
Loss: 
0.14949976245017574


# 3

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.60725744]
 [0.58488078]
 [0.60058734]]
Loss: 
0.08575272815998286


# 4

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.67155339]
 [0.64562902]
 [0.66787421]]
Loss: 
0.05234016695292596


# 5

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actua

Loss: 
0.00026790542671405263


# 112

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89591532]
 [0.87182826]
 [0.89913702]]
Loss: 
0.00026782153232062623


# 113

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89594093]
 [0.87185225]
 [0.89916001]]
Loss: 
0.0002677401425357957


# 114

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89596561]
 [0.87187522]
 [0.89918206]]
Loss: 
0.00026766106293193254


# 115

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89598938]
 [0.87189721]
 [0.8992032 ]]
Loss: 
0.000267584114416215


# 116

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8960123 ]
 [0.87191826]
 [0.89922348]]
Loss: 
0.00026750913200502424


# 117


 [0.89965937]]
Loss: 
0.0002617863804653945


# 224

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89673614]
 [0.8722762 ]
 [0.89965903]]
Loss: 
0.00026173636814184333


# 225

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89673845]
 [0.87227473]
 [0.89965868]]
Loss: 
0.0002616863722612305


# 226

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89674074]
 [0.87227325]
 [0.89965832]]
Loss: 
0.0002616363927903219


# 227

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89674302]
 [0.87227176]
 [0.89965796]]
Loss: 
0.0002615864296977335


# 228

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8967453 ]
 [0.87227026]
 [0.89965758]]
Loss: 
0.000261536482953


# 348

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8969926 ]
 [0.87206765]
 [0.89959184]]
Loss: 
0.00025565737126669643


# 349

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89699459]
 [0.87206593]
 [0.89959126]]
Loss: 
0.0002556093079683673


# 350

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89699658]
 [0.87206421]
 [0.89959068]]
Loss: 
0.0002555612596605165


# 351

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89699857]
 [0.87206249]
 [0.89959011]]
Loss: 
0.0002555132263343685


# 352

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89700056]
 [0.87206077]
 [0.89958953]]
Loss: 
0.0002554652079811493


# 353

Input (scaled): 
[[0.4 0.9]
 [0


# 466

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89722469]
 [0.87186646]
 [0.89952542]]
Loss: 
0.00025008708950251593


# 467

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89722663]
 [0.87186477]
 [0.89952487]]
Loss: 
0.00025004073626136756


# 468

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89722858]
 [0.87186308]
 [0.89952432]]
Loss: 
0.00024999439702056054


# 469

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89723052]
 [0.8718614 ]
 [0.89952378]]
Loss: 
0.0002499480717720877


# 470

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89723246]
 [0.87185971]
 [0.89952323]]
Loss: 
0.00024990176050794787


# 471

Input (scaled): 
[[0.4 0.9]


 [0.89946977]]
Loss: 
0.0002453399081498521


# 571

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89742687]
 [0.87169068]
 [0.89946925]]
Loss: 
0.0002452949691639035


# 572

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89742878]
 [0.87168902]
 [0.89946873]]
Loss: 
0.00024525004337786475


# 573

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89743069]
 [0.87168736]
 [0.89946821]]
Loss: 
0.00024520513078433727


# 574

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89743259]
 [0.87168571]
 [0.89946769]]
Loss: 
0.00024516023137594473


# 575

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8974345 ]
 [0.87168405]
 [0.89946716]]
Loss: 
0.0002451153451

# 678

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89762899]
 [0.87151459]
 [0.89941468]]
Loss: 
0.00024056128811794937


# 679

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89763086]
 [0.87151295]
 [0.89941418]]
Loss: 
0.00024051773316179854


# 680

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89763273]
 [0.87151132]
 [0.89941368]]
Loss: 
0.00024047419063937176


# 681

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8976346 ]
 [0.87150969]
 [0.89941319]]
Loss: 
0.00024043066054385814


# 682

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89763647]
 [0.87150806]
 [0.89941269]]
Loss: 
0.0002403871428684651


# 683

Input (scaled): 
[[0.4 0.9]
 

 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89784575]
 [0.87132535]
 [0.89935786]]
Loss: 
0.00023554800120610656


# 796

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89784758]
 [0.87132375]
 [0.89935739]]
Loss: 
0.00023550585613698943


# 797

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89784942]
 [0.87132215]
 [0.89935691]]
Loss: 
0.0002354637227394886


# 798

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89785125]
 [0.87132054]
 [0.89935644]]
Loss: 
0.00023542160100736785


# 799

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89785308]
 [0.87131894]
 [0.89935597]]
Loss: 
0.00023537949093440811


# 800

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]


# 912

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89805833]
 [0.87113941]
 [0.89930378]]
Loss: 
0.00023069464533247936


# 913

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89806013]
 [0.87113784]
 [0.89930333]]
Loss: 
0.00023065382475855243


# 914

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89806193]
 [0.87113626]
 [0.89930288]]
Loss: 
0.00023061301515813195


# 915

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89806373]
 [0.87113469]
 [0.89930243]]
Loss: 
0.00023057221652550124


# 916

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89806552]
 [0.87113311]
 [0.89930198]]
Loss: 
0.00023053142885495864


# 917

Input (scaled): 
[[0.4 0.9]
